[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
region = "us-west1"

[[services]]
name = "solana-trading-bot"
internalPort = 3000

[services.envs]
RUST_LOG = "info"