# Rust formatting configuration
# Documentation: https://rust-lang.github.io/rustfmt/

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Function formatting
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Comments and documentation
comment_width = 80
doc_comment_code_block_width = 100
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# Struct and enum formatting
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
struct_lit_single_line = true

# Match and control flow
match_arm_blocks = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
indent_style = "Block"

# String formatting
format_strings = true
format_macro_matchers = true

# Code organization
use_small_heuristics = "Default"
binop_separator = "Front"
combine_control_expr = true
condense_wildcard_suffixes = false

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Advanced options
unstable_features = false
skip_children = false

# Specific style preferences
empty_item_single_line = true
force_explicit_abi = true
format_code_in_doc_comments = false
hex_literal_case = "Preserve"
overflow_delimited_expr = false
remove_nested_parens = true
short_array_element_width_threshold = 10
single_line_if_else_max_width = 50
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
type_punctuation_density = "Wide"
where_single_line = false

# Ignore certain patterns
ignore = [
    "target/",
    "tests/fixtures/"
]